### ISSUE TITLE
Reboot and shutdown asks for root password

### ISSUE THREAD

**Issue by jmfergeau** [kppleos/org.kpple.kppleMenu#32]
Kpple now asks for root permissions when asked to reboot or shutdown. Before the recent updates of plasma, it wasn't asking for them.

I see in the settings the command for reboot and shutdown are respectively `/sbin/reboot` and `/sbin/shutdown now` 

I guess the work around would be to replace them with respectively `qdbus org.kde.ksmserver /KSMServer logout 0 1 1` and `qdbus org.kde.ksmserver /KSMServer logout 0 2 1`. 

[(more info on how the plasma logout screen works)](https://forum.endeavouros.com/t/tip-logout-of-plasma-session-from-the-terminal/8699/2)

**Comment by eduard-sukharev** [comment]
More to that, KDE5 has different convenience dbus endpoints:
```sh
qdbus ord.kde.Shutdown /Shutdown logout
qdbus ord.kde.Shutdown /Shutdown logoutAndShutdown
qdbus ord.kde.Shutdown /Shutdown logoutAndReboot
qdbus org.kde.Solid.PowerManagement /org/kde/Solid/PowerManagement/Actions/SuspendSession suspendToRam
```

**Comment by jmfergeau** [comment]
somedays after i posted it, it was fixed. Last time i used kde, like last week, it was still working like a charm. :p

Closing it since the problem didn't appeared for months now.
